behaviors:
  simple_deer:
    trainer_type: ppo
    hyperparameters:
      batch_size: 64
      buffer_size: 100
      learning_rate: 3.0e-5
      beta: 1.0e-2
      epsilon: 0.1
      lambd: 0.95
      num_epoch: 4
      learning_rate_schedule: linear
      beta_schedule: constant
      epsilon_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 1
    reward_signals:
      extrinsic:
        gamma: 0.9
        strength: 1.0
    max_steps: 100000
    time_horizon: 64
    summary_freq: 1000
    keep_checkpoints: 5
    checkpoint_interval: 25000

  simple_wolf:
    trainer_type: ppo
    hyperparameters:
      batch_size: 64
      buffer_size: 100
      learning_rate: 3.0e-5
      beta: 5.0e-3
      epsilon: 0.1
      lambd: 0.95
      num_epoch: 4
      learning_rate_schedule: linear
      beta_schedule: constant
      epsilon_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 1
    reward_signals:
      extrinsic:
        gamma: 0.9
        strength: 1.0
    max_steps: 100000
    time_horizon: 64
    summary_freq: 1000
    keep_checkpoints: 5
    checkpoint_interval: 25000